package com.thevalenciandev.algorithms.str;

/**
 * 389. Find the Difference https://leetcode.com/problems/find-the-difference/
 * <p>
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 * <p>
 * Constraints:
 * <p>
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        if (s.length() == 0) {
            return t.charAt(0);
        }

        int[] counts = new int[26];
        for (int i = 0; i < s.length(); i++) {
            int si = s.charAt(i) - 'a';
            int ti = t.charAt(i) - 'a';
            counts[si]++;
            counts[ti]--;
        }
        counts[t.charAt(t.length() - 1) - 'a']--;

        for (int i = 0; i < t.length(); i++) {
            if (counts[i] != 0) {
                return (char) ('a' + i);
            }
        }

        throw new RuntimeException("t's length should be s's length + 1");
    }
}
